source 'https://rubygems.org'

gem 'rails', '4.2.5'
gem 'sqlite3'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'spring'
gem 'devise', '~> 3.5', '>= 3.5.6'
gem 'bootstrap-sass', '~> 3.3', '>= 3.3.6'
gem 'acts_as_votable', '~> 0.10.0'
gem 'simple_form', '~> 3.0.2'
gem 'tinymce-rails', '~> 4.3', '>= 4.3.3'
gem 'font-awesome-rails', '~> 4.5', '>= 4.5.0.1'
gem 'will_paginate-bootstrap', '~> 1.0', '>= 1.0.1'